# Generated by Django 3.1.2 on 2021-01-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201218_1626'),
        ('api', '0002_auto_20210128_1411'),
    ]

    operations = [
    ]
